### PR TITLE
Keep enclosing class

### LINKED ISSUE #99: IllegalArgumentException: No enclosing component class found for interface
**Stacktrace:**
```
Caused by: java.lang.IllegalArgumentException: No enclosing component class found for interface com.example.ExampleComponent$Builder
  at com.yandex.yatagan.common.Loader__LoadImplementationKt.loadImplementationByBuilderClass(SourceFile:31)
  at com.yandex.yatagan.common.Loader.loadImplementationByBuilderClass(SourceFile:1)
  at com.yandex.yatagan.Yatagan.builder(SourceFile:51)
```

**Usage:**
Component:
```
package com.example

@Component
interface ExampleComponent {
    
   @Component.Builder
    interface Builder {
        fun build()
    }
}
```
Component usage:
```
val component = Yatagan.builder(ExampleComponent::class.java).build()
```

**Environment:**
Android Gradle Plugin 8.1.0
R8 8.1.59
openjdk 17.0.8.1

### PR DESCRIPTION
**Pull request by bacecek**
Fixes #99

### CODE REVIEW

**Comment by bacecek** [comment]
@Jeffset JFYI:
`proguard-android-optimize.txt` (default R8 config) already contains `-keepattributes` rule: https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:build-system/gradle-core/src/main/resources/com/android/build/gradle/proguard-common.txt;l=1-8?q=proguard-common

Retrofit also contains it: https://github.com/square/retrofit/blob/master/retrofit/src/main/resources/META-INF/proguard/retrofit2.pro#L3.

So I personally don't think that declaring `-keepattributes` rule is something bad. Yatagan already contains `-keep` rules which have a greater impact on the size and startup time of the application in large projects than removing class attributes. And it's really hard to find a project where `-keepattributes` rule will not be delivered with one of external libraries or by AGP.

**Comment by Jeffset** [comment]
Thanks for the PR!

Yes, I was concerned about the idea of imposing global `-keepattributes` rules on the clients, as Yatagan needs this only in one place and that can even be worked around, as you did. Well, if these `-keepattributes` are very common and often other libraries have them, I guess it would be safe enough to have them in Yatagan too. But the workaround with the class name is still a bit better, imo, because it has no cost that I know of.

So let's go with the implemented approach for now. And if we find some downsides to it, we'll modify the minifier config as you initially suggested.

**Comment by Jeffset** [comment]
> Yatagan already contains `-keep` rules which have a greater impact on the size and startup time of the application in large projects than removing class attributes.

Btw, how are the existing rules impact the size and startup time? If they are, that should be fixed.

```
# (1)
-keep class **.Yatagan$* {
    # Keep creating methods - called via reflection.
    public * autoBuilder();
    public * builder();
}
# (2)
-keep @com.yandex.yatagan.Component interface *
-keep @com.yandex.yatagan.Component$Builder interface *
```
The rule (1) keeps just the two entry-point methods and the name of the class, right? Everything else inside the generated component implementation is still supposed to be eligible for optimization and mangling, isn't it?

And rules (2) just keep the component/builder interfaces. They have no executable code, as they are just interfaces, so no performance penalties should come of it.

Please, correct me if I'm wrong in interpreting the proguard rules meaning!

**Comment by bacecek** [comment]
> Please, correct me if I'm wrong in interpreting the proguard rules meaning!

Sorry for my take, I was wrong about keep rule.

**Review by Jeffset — APPROVED** [review]

**Pull request merged**
